/** Auto-generated by scripts/generate-build-info.mjs — do not edit manually. */

export const EXTENSION_BUILD_INFO = {
  version: "0.3.0",
  sourceUpdatedAt: "2026-06-04T12:33:43.362Z",
  component: "sayane-extension",
} as const;
