import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const extRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

test("sidepanel initializes resident app summary panel", () => {
  const src = readFileSync(join(extRoot, "src", "sidepanel.ts"), "utf8");
  assert.ok(src.includes("initResidentAppSidepanel"));
  assert.ok(src.includes("residentAppUi = initResidentAppSidepanel"));
  assert.ok(src.includes("await residentAppUi.refresh()"));
  assert.ok(src.includes("void residentAppUi?.handleCandidatesChanged(candidateId)"));
});

test("resident app sidepanel reads bootstrap and home state", () => {
  const src = readFileSync(join(extRoot, "src", "resident-app-sidepanel.ts"), "utf8");
  assert.ok(src.includes("readCandidateDiff"));
  assert.ok(src.includes("readCandidateLineage"));
  assert.ok(src.includes("loadCurrentReviewSession"));
  assert.ok(src.includes("peekCandidatesFocusId"));
  assert.ok(src.includes("readAppContract"));
  assert.ok(src.includes("readHomeScreenState"));
  assert.ok(src.includes("readCandidateDetailScreenState"));
  assert.ok(src.includes("readCandidateQueueScreenState"));
  assert.ok(src.includes("readDaemonPanelScreenState"));
  assert.ok(src.includes("resident_app.meta"));
  assert.ok(src.includes("resident_app.detail."));
  assert.ok(src.includes("resident_app.action_hint."));
  assert.ok(src.includes("resident_app.summary."));
  assert.ok(src.includes("resident_app.queue."));
  assert.ok(src.includes("resident_app.link."));
  assert.ok(src.includes("showDaemonPanel"));
  assert.ok(src.includes("showCandidateDetail"));
  assert.ok(src.includes("loadCandidateQueue"));
  assert.ok(src.includes("focusCandidate"));
  assert.ok(src.includes("fallbackToQueueAfterDetailFailure"));
  assert.ok(src.includes("formatDetailUnavailable"));
  assert.ok(src.includes("renderDetailDiff"));
  assert.ok(src.includes("renderDetailLineage"));
  assert.ok(src.includes("renderDetailActionHints"));
  assert.ok(src.includes("renderDetailPanelState"));
  assert.ok(src.includes("renderQueuePanelState"));
  assert.ok(src.includes("syncActiveReviewState"));
  assert.ok(src.includes("styleActiveCandidateButton"));
  assert.ok(src.includes("activeReviewButtonReason"));
  assert.ok(src.includes("handleCandidatesChanged"));
  assert.ok(src.includes("refreshVisibleState"));
  assert.ok(src.includes("lastHomeState"));
  assert.ok(src.includes("lastQueueState"));
  assert.ok(src.includes("lastDetailState"));
  assert.ok(src.includes("readCandidateDetailScreenState(send, lastDetailCandidateId)"));
  assert.ok(src.includes("readCandidateQueueScreenState(send)"));
  assert.ok(src.includes("readHomeScreenState(send)"));
  assert.ok(src.includes("prioritizeActiveReviewItem"));
  assert.ok(src.includes("renderSummaryEntryList"));
  assert.ok(src.includes("renderPlainTextList"));
  assert.ok(src.includes("renderKeyValueRecord"));
  assert.ok(src.includes("RESIDENT_APP_DISPLAY_VALUE_KEYS"));
  assert.ok(src.includes("RESIDENT_APP_DISPLAY_FIELD_KEYS"));
  assert.ok(src.includes("RESIDENT_APP_DISPLAY_PHRASE_KEYS"));
  assert.ok(src.includes("localizeFieldKey"));
  assert.ok(src.includes("localizeReviewSessionSource"));
  assert.ok(src.includes("review.session.source."));
  assert.ok(src.includes('kind === "manual"'));
  assert.ok(src.includes("createResidentActionButton"));
  assert.ok(src.includes("appendResidentActionRow"));
  assert.ok(src.includes("buildHomeSummaryCards"));
  assert.ok(src.includes("buildQueueSummaryEntries"));
  assert.ok(src.includes("buildDetailActionEntries"));
  assert.ok(src.includes("buildDetailActionHintEntries"));
  assert.ok(src.includes("buildDetailLineageEntries"));
  assert.ok(src.includes("buildDetailDiffEntries"));
  assert.ok(src.includes("buildDetailSummaryEntries"));
  assert.ok(src.includes("const rawCandidateId = typeof item.candidate_id === \"string\" ? item.candidate_id : null;"));
  assert.ok(src.includes("disabled: rawCandidateId == null"));
  assert.ok(src.includes("rawCandidateId != null"));
  assert.ok(src.includes("resident_app.queue.active_candidate"));
  assert.ok(src.includes("resident_app.queue.active_present"));
  assert.ok(src.includes("resident_app.queue.active_missing"));
  assert.ok(src.includes("resident_app.queue.active_source"));
  assert.ok(src.includes("resident_app.queue.active_count"));
  assert.ok(src.includes("resident_app.detail.active_source"));
  assert.ok(src.includes("resident_app.detail.active_count"));
  assert.ok(src.includes("resident_app.detail.active_review_note"));
  assert.ok(src.includes("resident_app.detail.active_review_match"));
  assert.ok(src.includes("resident_app.detail.active_review_mismatch"));
  assert.ok(src.includes("resident_app.active_button.unavailable"));
  assert.ok(src.includes("resident_app.active_button.current"));
  assert.ok(src.includes("resident_app.active_button.available"));
  assert.ok(src.includes("resident-app-queue-open-active-review"));
  assert.ok(src.includes("resident-app-detail-back-active-review"));
  assert.ok(src.includes('screen: "active_review_detail"'));
  assert.ok(src.includes('screen: "active_review_detail"'));
  assert.ok(src.includes('key: "active_review_source"'));
  assert.ok(src.includes('key: "active_review_count"'));
  assert.ok(src.includes('key: "active_review_presence"'));
  assert.ok(src.includes('t("resident_app.summary.active_review_present")'));
  assert.ok(src.includes('t("resident_app.summary.active_review_missing")'));
  assert.ok(src.includes("resident_app.detail_fallback_queue"));
  assert.ok(src.includes("resident_app.active."));
  assert.ok(src.includes("resident_app.detail.active_review"));
  assert.ok(src.includes("resident_app.field.status"));
  assert.ok(src.includes("resident_app.value.review_required"));
  assert.ok(src.includes('selection: "resident_app.value.selection"'));
  assert.ok(src.includes('page: "resident_app.value.page"'));
  assert.ok(src.includes('manual: "resident_app.value.manual"'));
  assert.ok(src.includes("resident_app.phrase.reason_missing_directory_apply"));
});

test("sidepanel delegates storage changes to resident app handler", () => {
  const src = readFileSync(join(extRoot, "src", "sidepanel.ts"), "utf8");
  assert.ok(src.includes("watchCandidatesChanged((candidateId) => {"));
  assert.ok(src.includes("residentAppUi?.handleCandidatesChanged(candidateId)"));
});

test("sidepanel html exposes resident app summary containers", () => {
  const html = readFileSync(join(extRoot, "sidepanel.html"), "utf8");
  assert.ok(html.includes('<html lang="en">'));
  assert.ok(html.includes('id="resident-app-panel"'));
  assert.ok(html.includes('id="resident-app-active-review"'));
  assert.ok(html.includes('id="resident-app-summary-cards"'));
  assert.ok(html.includes('id="resident-app-review-items"'));
  assert.ok(html.includes('id="resident-app-daemon-actions"'));
  assert.ok(html.includes('id="resident-app-quick-links"'));
  assert.ok(html.includes('id="resident-app-queue-panel"'));
  assert.ok(html.includes('id="resident-app-queue-summary"'));
  assert.ok(html.includes('id="resident-app-queue-open-active-review"'));
  assert.ok(html.includes('id="resident-app-queue-items"'));
  assert.ok(html.includes('id="resident-app-detail-panel"'));
  assert.ok(html.includes('id="resident-app-detail-summary"'));
  assert.ok(html.includes('id="resident-app-detail-lineage"'));
  assert.ok(html.includes('id="resident-app-detail-open-review"'));
  assert.ok(html.includes('id="resident-app-detail-back-queue"'));
  assert.ok(html.includes('id="resident-app-detail-back-active-review"'));
  assert.ok(html.includes('id="resident-app-detail-action-hints"'));
  assert.ok(html.includes('id="resident-app-detail-diff"'));
  assert.ok(html.includes('id="resident-app-detail-content"'));
  assert.ok(html.includes('id="resident-app-daemon-panel"'));
  assert.ok(html.includes('id="resident-app-daemon-summary"'));
  assert.ok(html.includes("resident-app-link-button-active"));
});

test("resident app locale keys stay aligned across ja and en", () => {
  const ja = JSON.parse(readFileSync(join(extRoot, "locale/ja.json"), "utf8")) as Record<string, string>;
  const en = JSON.parse(readFileSync(join(extRoot, "locale/en.json"), "utf8")) as Record<string, string>;

  const jaResidentKeys = Object.keys(ja).filter((key) => key.startsWith("resident_app."));
  const enResidentKeys = Object.keys(en).filter((key) => key.startsWith("resident_app."));

  assert.deepEqual([...jaResidentKeys].sort(), [...enResidentKeys].sort());
  assert.ok(ja["resident_app.active.current"].includes("アクティブレビュー"));
  assert.ok(ja["resident_app.daemon_cleanup"].includes("クリーンアップ"));
  assert.ok(ja["resident_app.daemon_repair"].includes("修復"));
  assert.ok(ja["resident_app.field.status"].includes("状態"));
  assert.ok(ja["resident_app.value.review_required"].includes("レビュー"));
  assert.equal(ja["resident_app.value.pending"], "保留");
  assert.equal(ja["resident_app.value.evaluated"], "評価済み");
  assert.equal(ja["resident_app.value.approved"], "承認済み");
  assert.equal(ja["resident_app.value.rejected"], "却下済み");
  assert.equal(ja["resident_app.value.manual"], "手動");
  assert.ok(ja["resident_app.phrase.reason_missing_directory_apply"].includes("不足ディレクトリ"));
  assert.ok(ja["resident_app.phrase.reason_runtime_init_manual_review"].includes("手動レビュー"));
  assert.ok(ja["resident_app.phrase.reason_state_stable_refresh"].includes("デーモン状態"));
  assert.ok(en["resident_app.active.current"].includes("active review"));
  assert.ok(en["resident_app.field.status"].includes("Status"));
  assert.ok(en["resident_app.value.review_required"].includes("review"));
});
